### ISSUE TITLE
Rule with multiple constants not applied

### ISSUE THREAD

**Issue by chlewe** [karmaresearch/vlog#2]
Hello,
I wrote a program that computes the sequence of succeeding binary numbers up to length 2. However, vlog does not apply a specific rule for some reason, even though this rule _should_ be applicable. Am I making any mistakes here and is this vlog's intended behaviour, or is this a bug?

Details:
`rules`
```
succ2(0,X,0,Y) :- succ1(X,Y)
succ2(1,X,1,Y) :- succ1(X,Y)
succ2(0,X,1,Y) :- last1(X),first1(Y)
```
`first1.csv`
```
0
```
`last1.csv`
```
1
```
`succ1.csv`
```
0,1
```
`edb.conf`
```
EDB0_predname=first1
EDB0_type=INMEMORY
EDB0_param0=.
EDB0_param1=first1
EDB1_predname=last1
EDB1_type=INMEMORY
EDB1_param0=.
EDB1_param1=last1
EDB1_predname=succ1
EDB1_type=INMEMORY
EDB1_param0=.
EDB1_param1=succ1
```

I ran the following command to materialise:
```
$ ./vlog mat --edb edb.conf --rules rules --storemat_path . --storemat_format csv --decompressmat 1
```

The materialisation of `succ2` looked like this:
```
0,0,0,1
1,0,1,1
```

But I expected to see this in the materialisation as well:
```
0,1,1,0
```

It can be derived by applying the third rule, which is the only one that includes multiple constants. Could this be the reason for the bug, if it is a bug?

**Comment by mmarx** [comment]
You're defining EDB1 twice, overwriting the definition for last1.

**Comment by chlewe** [comment]
Thank you for pointing that out. This was indeed a silly mistake of mine; vlog itself works correctly with the fixed `edb.conf`.
