### ISSUE TITLE
VLog.addData() should ignore null data

### ISSUE THREAD

**Issue by mkroetzsch** [karmaresearch/vlog#25]
The method karmaresearch.vlog.VLog.addData() in the Java interface does not accept incomplete arrays but will rather throw "karmaresearch.vlog.EDBConfigurationException: null data". It would be better if it could just ignore the null data. Managing arrays is somewhat costly, and making a copy of a (large) array just to truncate the unused places seems wasteful.

**Comment by CerielJacobs** [comment]
Fixed
