### ISSUE TITLE
N-Triples parser interprets some terms incorrectly

### ISSUE THREAD

**Issue by mkroetzsch** [karmaresearch/vlog#32]
VLog will accept arbitrary strings in the position of RDF terms. Apparently those strings are turned into VLog constants using the string as a name. In essence, Turtle only has the following types of terms:
* IRIs, written with <>, such as `<http://example.org>`
* Literals, of the expanded form, such as `"2"^^<http://www.w3.org/2001/XMLSchema#integer>`
* Some builtin literal abbreviations for string (e.g., `"string"`), numbers (e.g., `1234.56` -- no quotes!), booleans (`true` or `false`)
* Blank nodes, such as `_:blank1`

Therefore, triples like
```<http:example.org/suject>  <http:example.org/predicate> object .```
should not work, but they do. 

Literal abbreviations should be expanded by adding their XSD type (as done only for plain strings now). For example,
```<http:example.org/suject>  <http:example.org/predicate> 42 .```
should be read as
```<http:example.org/suject>  <http:example.org/predicate> "42"^^<http://www.w3.org/2001/XMLSchema#integer> .```
The form of the number determines the datatype to be used.

The rather short [N-Triples RDF 1.1. specification](https://www.w3.org/TR/n-triples/) gives the details.

**Comment by CerielJacobs** [comment]
The N-Triples specification does not specify the builtin literal abbreviations for numbers or booleans. Other than that, the kognac nt parser has now been updated.

**Comment by mkroetzsch** [comment]
Ah, indeed, only strings are expanded in nt. This already helps a lot. I had encountered the problem when trying to do data integration across sources.
