### ISSUE TITLE
Vlog.start cannot find .csv.gz / .nt / .nt.gz files

### ISSUE THREAD

**Issue by chlewe** [karmaresearch/vlog#4]
Hello,
I currently adding support for `.csv.gz`, `.nt` and `.nt.gz` files to VLog4J and while doing that, I noticed some strange behaviour: The method `karmaresearch.vlog.Vlog.start` does not seem to 
to check for the new extensions. Instead, it outputs the error message `Could not open PATH/FILENAME.csv`.

As an example, take the following EDB config:
```
EDB0_predname=q
EDB0_type=INMEMORY
EDB0_param0=src/test/data/input/
EDB0_param1=unaryFactsZipped
```

The file `src/test/data/input/unaryFactsZipped.csv.gz` exists, but `Vlog.start` exists with the error `Could not open src/test/data/input//unaryFactsZipped.csv`.

This issue can be observed while testing the latest version of the [`new-extensions` branch](https://github.com/knowsys/vlog4j/tree/new-extensions) of VLog4J. _(I pulled, built and used the latest `master` version of VLog)_

Interestingly, the issue does not occur while using vlog itself on the command line. Maybe, only the method `Vlog.start` exhibits the bug.

**Comment by CerielJacobs** [comment]
Hi Christian,

I did not try it through VLog4J, but did try it through the low-level Java API from VLog, and cannot reproduce this problem.
For me, it works.

Ceriel

**Comment by chlewe** [comment]
Hello Ceriel,
Thank you for responding to my issues in such a short time. After reading your reply, I wrote an independent Java class to test the raw Java API of VLog, which turned out to work perfectly. After further investigation, I could find and eliminate the problem, which resided in VLog4J's code and not VLog's.

**Comment by mkroetzsch** [comment]
Hi Christian, if you fixed something in VLog4j, which pull request was that? Issues should only be closed after the fixes have been reviewed and merged into master.

**Comment by CerielJacobs** [comment]
This was an issue raised in karmaresearch/vlog, not in VLog4j.

Best,	Ceriel

**Comment by chlewe** [comment]
Hello Markus,
The `master` of VLog4J does not exhibit the bug, because it does not support gzipped input files yet. However, I will incorporate the fix into the branch `new-extensions`, for which I will create a pull request to `master`, once all new features have been implemented and properly tested. Should, for whatever reason, a similar problem arise in VLog4J again, I will create a new issue there.
