### ISSUE TITLE
Problems if head is a conjunction with constants

### ISSUE THREAD

**Issue by phil-hanisch** [karmaresearch/vlog#46]
Hi, there might be a problem with the reasoning if the head of a rule is a conjunction that uses constants. In this situation, some facts are not inferred.

I have added an example, which illustrate the problem:
[example.txt](https://github.com/karmaresearch/vlog/files/4550376/example.txt)

**Comment by larryjgonzalez** [comment]
I've replicated the example above in VLog.

`edb.conf`:
```EDB0_predname=vertex
EDB0_type=INMEMORY
EDB0_param0=.
EDB0_param1=vertex
EDB1_predname=edge
EDB1_type=INMEMORY
EDB1_param0=.
EDB1_param1=edge
```

with `vertex.csv` containing:
```
1
2
```

`edge.csv` containing:
```
1,2
```


and the rules
```
coloured(X,blue), coloured(X,red):-vertex(X)
sameColour(C):-edge(X,Y),coloured(X,C),coloured(Y,C)
```

Vlog (master, v1.3.2, v1.3.1, I did not test other versions) infers for `coloured`:
```
1,blue
1,red
2,blue
2,red
```

which is correct; but it infers for `sameColour`
```
blue
```

which is incomplete.
