### ISSUE TITLE
Java API: Enable query answering via QueryResultIterator

### ISSUE THREAD

**Issue by mkroetzsch** [karmaresearch/vlog#47]
RuleWerk now uses QueryResultIterator rather than TermQueryResultIterator for performance reasons. The required query method is public in VLog, but its parameters must be prepared with a non-public method extractTerms() that is now re-implemented in RuleWerk. It would be good if VLog had a clean way to get a low-level QueryResultIterator for a query, or at least would make extractTerms() public.

**Comment by CerielJacobs** [comment]
Would you be happy with a method that gives you a QueryResultIterator when provided with an Atom? Obviously, it cannot be called “query” then.

**Comment by mkroetzsch** [comment]
Yes, such a method would be easiest to use from our side.
