### ISSUE TITLE
Error libc++abi.dylib: terminating with uncaught exception of type int

### ISSUE THREAD

**Issue by irina-dragoste** [karmaresearch/vlog#49]
During reasoning with the rulewerk code below, I get the following C++ error: "libc++abi.dylib: terminating with uncaught exception of type int"

```
final InputStream input = new FileInputStream("src/test/resources/kb-21facts.txt");
final KnowledgeBase kb = RuleParser.parse(input);
try (Reasoner reasoner = new VLogReasoner(kb)) {
		reasoner.setLogFile("src/test/resources/logs/log" + System.currentTimeMillis() + ".txt");
		reasoner.setLogLevel(LogLevel.DEBUG);
		reasoner.reason();
}
```
I attach the kb file  [kb-21facts.txt](https://github.com/karmaresearch/vlog/files/4866075/kb-21facts.txt)
and the log file [log1593714964286.txt](https://github.com/karmaresearch/vlog/files/4866079/log1593714964286.txt).

**Comment by CerielJacobs** [comment]
Closed
