### ISSUE TITLE
Unzipped CSV facts are corrupted

### ISSUE THREAD

**Issue by chlewe** [karmaresearch/vlog#5]
When I gzip a `.csv` file to a `.csv.gz` and use that with VLog _(on the command line)_, it successfully reads the file, but it adds the filename as an additional fact. Furthermore, the one fact of the original archive is renamed; is this intended behaviour?

The original file, `first1.csv`, looked like this before gzipping:
```
0
```
I used the standard tool for gzipping on Linux, which is `tar`, and deleted the original CSV after that.
```
$ tar -czf first1.csv.gz first1.csv
$ rm first1.csv
```
After reasoning, I looked into the materialisation and found `first`:
```
first1.csv
0_0_1
```
As you can see, it looks somewhat corrupted. Those two _(instead of one)_ facts were also used to derive other facts during reasoning, leading to further corruption.

Am I gzipping in the wrong way or is this a bug of VLog?

**Comment by CerielJacobs** [comment]
You are gzipping the wrong way. Use “gzip”, not tar, because then you get a gzipped tar-file.

Ceriel
