### ISSUE TITLE
Wrong term type in result from Trident

### ISSUE THREAD

**Issue by mkroetzsch** [karmaresearch/vlog#55]
When I query a trident data source from VLog, strings in the RDF data are returned as abstract constants with IRIs. To reporduce:
- Create a trident database from an RDF file that contains a string literal "string"
- Use that trident database in VLog as a data source and query for the data.
- The result should be <"string"> where "string" was expecteed

**Comment by CerielJacobs** [comment]
I am trying to reproduce this with the low-level VLog Java bindings, but failing miserably. I created a trident database, with one entry:
<aap> <noot> “mies”
If I query this using a TermQueryIterator, I get
[CONSTANT: <aap>, CONSTANT: <noot>, CONSTANT: "mies”]

which is correct, I think.

**Comment by mkroetzsch** [comment]
After some joint debugging, it turned out that the incorrect term in VLog is an untyped string ```"string"``` (distinct from the usual version ```"string"^^xsd:string```). Rulewerk wrongly interpreted this type-less constant to refer to an abstract constant. This has been changed in Rulewerk in [a recent commit](https://github.com/knowsys/rulewerk/pull/181/commits/90fbe1ad895eb21bcf0a3566d44a2bbe9d7bc4a4).

This fixes only the appearance in Rulewerk. The string should still be encoded with xsd:string in VLog in order to join correctly with other strings from RDF sources. As it is now, a Trident database built from an RDF file with a string will not join with that same RDF file.

**Comment by irina-dragoste** [comment]
Fixed, SPARQL results remain to be tested in open issue https://github.com/knowsys/rulewerk/issues/223.
