### ISSUE TITLE
Incomplete Derivation from a Datalog Rule Set

### ISSUE THREAD

**Issue by smennicke** [karmaresearch/vlog#62]
Consider the following program:

`edb.conf`:
```
EDB0_predname=t
EDB0_type=INMEMORY
EDB0_param0=.
EDB0_param1=t
``` 
`t.csv`:
```
1,a,3
3,b,4
3,c,4
``` 
`rules`:
```
q(Y,X) :- t(X,b,Y)
p(X,Z) :- t(X,a,Y), t(Y,c,Z)
r(X,Z) :- q(Y,Z), p(X,Y)
``` 

After running `./vlog mat --edb edb.conf --storemat_path . --storemat_format csv --decompressmat 1 --rules rules` I can see all predicates being materialized, especially `r`:
```
1,3
```
which is the expected result. If, however, I change the last rule by switching the order of the body atoms, i.e., `rules1`:
```
q(Y,X) :- t(X,b,Y)
p(X,Z) :- t(X,a,Y), t(Y,c,Z)
r(X,Z) :- p(X,Y), q(Y,Z)
```
the call `./vlog mat --edb edb.conf --storemat_path . --storemat_format csv --decompressmat 1 --rules rules1`, yields no materialization of `r`, whereas it should produce the same as before.

I have tested this case with and without debug mode from commit ee8267a.

**Comment by CerielJacobs** [comment]
I think I fixed this issue. @smennicke can you please check?

**Comment by smennicke** [comment]
Yes, I think it is fixed now. I have checked with the original example as well as a similar one. Thank you!
