### ISSUE TITLE
out of memory for rules with many body atoms

### ISSUE THREAD

**Issue by irina-dragoste** [karmaresearch/vlog#65]
For a program with no data and a single rule with 271 ground unary body atoms, VLog runs out of memory while trying to compute execution plans (when out of RAM, uses swap space of up to 60GB). Nevertheless, this rule is never applicable.
Please find attached 
[the rule file](https://github.com/karmaresearch/vlog/files/6122343/bug.injign.datalog.txt) and 
[the debug log](https://github.com/karmaresearch/vlog/files/6122346/DEBUG_1615450216155.log.txt).
Note that for a rule with 12 body atoms, materialization also does not terminate. (it does in 33 seconds for 11 body atoms).

**Comment by mmarx** [comment]
Here's a snapshot from the heap profile when run under massif:
![massif screenshot](https://user-images.githubusercontent.com/675854/110777885-f17ef500-8261-11eb-9b69-b69d6d95be63.png)

When configuring `ResultDeg` as an EDB predicate, it looks a bit different, but still uses lots of memory:
![massif screenshot, with ResultDeg configured as EDB](https://user-images.githubusercontent.com/675854/110778020-1a06ef00-8262-11eb-84d9-8a4bae1a5969.png)

**Comment by irina-dragoste** [comment]
Issue fixed
