### ISSUE TITLE
Crash when checking RJA

### ISSUE THREAD

**Issue by irina-dragoste** [karmaresearch/vlog#77]
When running `checkCycles(RJA)` from the `VLog.java`
for a VLog instance strarted with the rule set below, the following crash occurs: 
`libc++abi.dylib: terminating with uncaught exception of type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >`

```
R(?x,!y), D(!y) :- C(?x) .
S(?x,!y), E(!y) :- D(?x) .		
V(?x,!y), C(!y) :- E(?x) .
		
```
The DEBUG level log file [debug.txt](https://github.com/karmaresearch/vlog/files/7109809/debug.txt) is attached.

**Comment by CerielJacobs** [comment]
Fixed.
