### ISSUE TITLE
JA classification problem

### ISSUE THREAD

**Issue by CerielJacobs** [karmaresearch/vlog#79]
With rules

P(Y,Z) :- P(X,Y), C(Y)

and empty edb.conf, the command

vlog cycles --alg JA --rules rules -e edb.conf

does not classify this rule-set as JA, but it should.

**Comment by irina-dragoste** [comment]
![image](https://user-images.githubusercontent.com/26414082/132544486-6f3ecd6b-696c-4274-9916-68f7baed8ab1.png)
