### ISSUE TITLE
Missing RMFC classification P(Y,Z) :- P(X,Y)

### ISSUE THREAD

**Issue by irina-dragoste** [karmaresearch/vlog#80]
With rules

P(Y,Z) :- P(X,Y)

and empty edb.conf, the command

vlog cycles --alg RMFC --rules rules -e edb.conf

Returns INCONCLUSIVE result, but this ruleset should be RMFC.

**Comment by irina-dragoste** [comment]
![image](https://user-images.githubusercontent.com/26414082/132526667-4ff5470d-fc36-44b8-a4ce-91f5a7f42564.png)

**Comment by CerielJacobs** [comment]
Apparently, this also fixes issue #81.
