### ISSUE TITLE
Wrong RMFC classification

### ISSUE THREAD

**Issue by irina-dragoste** [karmaresearch/vlog#81]
With rules
R(x,y),D(y) :- C(x) .
S(x,y), E(y) :- D(x) .
V(x,y), C(y) :- E(x) .
R(z,x) :- S(x,y), V(y,z) .

vlog cycles --alg RMFC --rules rules -e edb.conf

classifies this rule-set as RMFC, but it is not.

**Comment by CerielJacobs** [comment]
@irina-dragoste : In issue #85, you acknowledge that this rule-set is not RMFA. Are you maintaining that is is not RMFC?

**Comment by CerielJacobs** [comment]
@irina-dragoste I think you do, because you say that the restricted chase will terminate.

**Comment by CerielJacobs** [comment]
Apparently, the fix to issue #80 also fixes this issue.
