### ISSUE TITLE
File paths for EDB configurations are wrongly interpreted on Windows

### ISSUE THREAD

**Issue by irina-dragoste** [karmaresearch/vlog#97]
For an EDB.config file on a Windows machine
```
EDB0_predname=r-1
EDB0_type=INMEMORY
EDB0_param0=D:\rulewerk\rulewerk-vlog\src\test\data\input
EDB0_param1=constantD
```
I get the following error when reasoning with any rule with EDB predicate name `r-`:

```
[0xf66f28325ab80c29 2022-08-27 21:14:20] ERROR  While importing data for predicate "r-1": could not open file /D:\rulewerk\rulewerk-vlog\src\test\data\input/constantD.nt nor /D:\rulewerk\rulewerk-vlog\src\test\data\input/constantD.csv nor gzipped versions
```
The path VLog should look for instead would be `D:\rulewerk\rulewerk-vlog\src\test\data\input\constantD.nt` 

In noticed this problem because [Rulewerk](https://github.com/knowsys/rulewerk) unit tests are failing on Windows due to this bug (ex:  [`VLogReasonerStateTest#testResetKeepExplicitDatabase()`](https://github.com/knowsys/rulewerk/blob/master/rulewerk-vlog/src/test/java/org/semanticweb/rulewerk/reasoner/vlog/VLogReasonerStateTest.java) )

If this fix requires a lot of changes anyway, it would perhaps be more maintainable if the EDB configuration would have a single parameter containing the path to the file, instead of the parent directory and the file name (without extension) as separate parameters.

**Comment by CerielJacobs** [comment]
I think I fixed this. Can you please try it with attached jar?
[jvlog-local.zip](https://github.com/karmaresearch/vlog/files/9443663/jvlog-local.zip)

**Comment by irina-dragoste** [comment]
> I think I fixed this. Can you please try it with attached jar? [jvlog-local.zip](https://github.com/karmaresearch/vlog/files/9443663/jvlog-local.zip)

It works, thank you!

**Comment by CerielJacobs** [comment]
Thanks for testing!
